AppAccount/urls.py
from django.urls import path
from .views import SignupView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

app_name = "AppAccount"

urlpatterns = [
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(
        template_name="AppAccount/login.html",
        extra_context={"title": "Login", "heading": "Login"}
    ), name="login"),
    path("logout/", LogoutView.as_view(
        template_name='AppAccount/logout.html',
        extra_context={"title": "Logout", "heading": "Log out successfully"},
        next_page=None
    ), name="logout"),
    path("profile/", login_required(TemplateView.as_view(
        template_name="AppAccount/profile.html",
        extra_context={"title": "User Profile", "heading": "User Profile"}
    )), name="profile"),
]

AppShowcase/urls.py
from django.urls import path
from .views import Tic_tac_toe, Connect_four


app_name = "AppShowcase"

urlpatterns = [
    # tic tac toe
    path("tic-tac-toe/", Tic_tac_toe.as_view(), name="tic-tac-toe"),
    # connect four
    path("connect-four/", Connect_four.as_view(), name="connect-four"),
]

ArgusWatcher/ArgusWatcher/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('ec2/', include("AppEasyDeploy.urls")),
    path('projects/', include("AppShowcase.urls")),
    path('admin/', admin.site.urls),
]

ArgusWatcher/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path("accounts/", include("AppAccount.urls")),
    path('projects/', include("AppShowcase.urls")),
    path('admin/', admin.site.urls),
]

templates/layout/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{title}}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
    />
    <script
      src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
      integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
      crossorigin="anonymous"
    ></script>
    {% block css %}{% endblock %}
    <!-- <script src="{% static 'js/main.js' %}"></script> -->
  </head>
  <body>
    {% include "layout/navbar.html" %} {% block main %}{% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
    {% block js %}{% endblock %}
  </body>
</html>

templates/layout/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom border-2">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Argus Watcher</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Blog</a>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Project
          </a>
          <ul class="dropdown-menu">
            <li>
              <a
                class="dropdown-item"
                href="{% url 'AppShowcase:tic-tac-toe' %}"
              >
                Tic-Tac-Toe
              </a>
            </li>
            <li>
              <a
                class="dropdown-item"
                href="{% url 'AppShowcase:connect-four' %}"
              >
                Connect Four
              </a>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li><a class="dropdown-item" href="#">Health</a></li>
            <li><hr class="dropdown-divider" /></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About Me </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Resume </a>
        </li>
      </ul>

      {% if user.is_authenticated %}
      <ul class="navbar-nav mb-2 mb-lg-0">
        <span class="navbar-text"> Hello, {{user.username}} </span>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <u>Profile Panel</u>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <u>Blog Panel</u>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'AppAccount:logout' %}">
            <u>Signout</u>
          </a>
        </li>
      </ul>
      {% else %}
      <a class="btn btn-sm btn-warning" href="{% url 'AppAccount:login' %}">
        Signin
      </a>
      {% endif %}
    </div>
  </div>
</nav>